# Install script for directory: C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/Demos

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files/BULLET_PHYSICS")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/DX11ClothDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/HelloWorld/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/MultiThreadedDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/OpenCLClothDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/OpenGL/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/AllBulletDemos/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/ConvexDecompositionDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/CcdPhysicsDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/BulletXmlImportDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/ConstraintDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/SliderConstraintDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/GenericJointDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/Raytracer/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/RagdollDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/ForkLiftDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/BasicDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/FeatherstoneMultiBodyDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/RollingFrictionDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/RaytestDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/VoronoiFractureDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/GyroscopicDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/FractureDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/Box2dDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/BspDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/MovingConcaveDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/VehicleDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/UserCollisionAlgorithm/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/CharacterDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/SoftDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/CollisionInterfaceDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/ConcaveConvexcastDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/SimplexDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/DynamicControlDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/ConvexHullDistance/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/DoublePrecisionDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/ConcaveDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/CollisionDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/ContinuousConvexCollision/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/ConcaveRaycastDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/GjkConvexCastDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/MultiMaterialDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/SerializeDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/InternalEdgeDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/Benchmarks/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/ThreadingDemo/cmake_install.cmake")
  include("C:/dev/projects/games_graphics/Amber3D/Dependencies/bullet-2.82-r2704/win64/Demos/VectorAdd_OpenCL/cmake_install.cmake")

endif()

